services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bolshoyzi-app
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: tail -f /dev/null
  postgres:
    image: postgres:15-alpine
    container_name: bolshoyzi_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
  privoxy:
    build:
      context: .
      dockerfile: Dockerfile.privoxy
    container_name: privoxy
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bolshoyzi_rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  minio:
    image: minio/minio
    container_name: bolshoyzi_minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  mongo:
    image: mongo:6
    container_name: bolshoyzi_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7-alpine
    container_name: bolshoyzi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pgdata:
  rabbitmq_data:
  minio_data:
  mongo_data:
  redis_data: