"""scripts_programs

Revision ID: 085016c6350e
Revises: 4bf0aa10532e
Create Date: 2025-08-31 18:10:58.378000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085016c6350e'
down_revision: Union[str, Sequence[str], None] = '4bf0aa10532e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('group', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scripts_programs',
    sa.Column('script_id', sa.String(length=26), nullable=False),
    sa.Column('program_id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('script_id', 'program_id')
    )
    op.drop_column('programs', 'output')
    op.drop_column('programs', 'input')
    op.drop_column('programs', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('group', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('programs', sa.Column('input', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('programs', sa.Column('output', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('scripts_programs')
    op.drop_table('scripts')
    # ### end Alembic commands ###
