"""ip_sites__fails_and_success_counters

Revision ID: 213170a788a1
Revises: 2daaea53c6af
Create Date: 2025-08-30 17:18:25.307460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213170a788a1'
down_revision: Union[str, Sequence[str], None] = '2daaea53c6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_sites', sa.Column('fails_count', sa.Integer(), nullable=True))
    op.add_column('ip_sites', sa.Column('success_count', sa.Integer(), nullable=True))
    op.add_column('ip_sites', sa.Column('fails_in_row', sa.Integer(), nullable=True))
    op.execute("UPDATE ip_sites SET fails_count=0, success_count=0, fails_in_row=0;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_sites', 'fails_in_row')
    op.drop_column('ip_sites', 'success_count')
    op.drop_column('ip_sites', 'fails_count')
    # ### end Alembic commands ###
