"""ip_sites

Revision ID: 2daaea53c6af
Revises: 44edea7fdbca
Create Date: 2025-08-30 15:34:33.045486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2daaea53c6af'
down_revision: Union[str, Sequence[str], None] = '44edea7fdbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_sites',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_sites')
    # ### end Alembic commands ###
