"""proxies__error

Revision ID: 44edea7fdbca
Revises: 274ce09ca36b
Create Date: 2025-08-30 12:15:15.124388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44edea7fdbca'
down_revision: Union[str, Sequence[str], None] = '274ce09ca36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxies', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxies', 'error')
    # ### end Alembic commands ###
