"""scripts_programs__desc

Revision ID: df7cec983208
Revises: 346592d83b49
Create Date: 2025-08-31 18:18:57.515246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df7cec983208'
down_revision: Union[str, Sequence[str], None] = '346592d83b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts_programs', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts_programs', 'desc')
    # ### end Alembic commands ###
