"""proxies__stats

Revision ID: f6472a2fa8ea
Revises: 213170a788a1
Create Date: 2025-08-30 17:41:34.990762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6472a2fa8ea'
down_revision: Union[str, Sequence[str], None] = '213170a788a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_sites', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.drop_column('ip_sites', 'failed_at')
    op.add_column('proxies', sa.Column('fails_count', sa.Integer(), nullable=True))
    op.add_column('proxies', sa.Column('success_count', sa.Integer(), nullable=True))
    op.add_column('proxies', sa.Column('fails_in_row', sa.Integer(), nullable=True))
    op.execute("UPDATE proxies SET fails_count=0, success_count=0, fails_in_row=0;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxies', 'fails_in_row')
    op.drop_column('proxies', 'success_count')
    op.drop_column('proxies', 'fails_count')
    op.add_column('ip_sites', sa.Column('failed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('ip_sites', 'verified_at')
    # ### end Alembic commands ###
