"""settings

Revision ID: fd8942d9c31b
Revises: f6472a2fa8ea
Create Date: 2025-08-31 11:36:57.205721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8942d9c31b'
down_revision: Union[str, Sequence[str], None] = 'f6472a2fa8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('is_debug', sa.Boolean(), nullable=False),
    sa.Column('proxies_monitor_interval_sec', sa.Integer(), nullable=False),
    sa.Column('autoheal_interval_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
